# Generated by Django 5.0.6 on 2024-06-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuati_app', '0007_alter_answerrecord_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('question_num', models.IntegerField(default=0, verbose_name='做题总数')),
                ('correct_percentage', models.FloatField(default=0.0, verbose_name='正确率')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='shuati_app.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户做题情况轨迹',
                'verbose_name_plural': '用户做题情况轨迹',
                'db_table': 'shuatiapp_user_activity',
            },
        ),
    ]
